# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Validate
  jobs:
  - job: Validate
    continueOnError: false
    steps:
      - publish: 1-terraform
        artifact: terraform_out
      - task: TerraformInstaller@0
        displayName: 'Use Terraform v0.12.6'
        inputs:
          terraformVersion: 0.12.6
      - task: TerraformCLI@0
        displayName: 'terraform init'
        inputs:
          command: init
          workingDirectory: 1-terraform
          backendType: azurerm
          backendServiceArm: 'Azure SPN'
          backendAzureRmResourceGroupName: 'AKSTerraform-RG'
          backendAzureRmStorageAccountName: 'aksstoragesocgen'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'aksterra'
      - task: TerraformCLI@0
        displayName: 'terraform validate'
        inputs:
         command: validate
         workingDirectory: 1-terraform
